definitions:
  contact__site_page:
    weight: -43
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
  standard__front_page:
    weight: -47
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  file_entity__types:
    enabled: false
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    weight: 0
  entity__media_type__collection:
    enabled: false
    menu_name: admin
    parent: system.admin_structure
    weight: 0
    expanded: false
  plugin__plugin_type__list:
    enabled: false
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    weight: 0
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
