node_search:
  advanced:
    types:
      supplemental: supplemental
      tweet: tweet
      blog: blog
      news: news
      safari: safari
      resource: resource
      country: country
      donate_page: donate_page
      staff: staff
      hostory: hostory
      history: history
      career: career
      landing_page: landing_page
      fact: fact
      project: project
      partner: partner
      landscape: landscape
      region: region
      species: species
      supplemental_sidebar: supplemental_sidebar
      hero_slideshow: hero_slideshow
      reasons: reasons
      ways_to_give: ways_to_give
    languages:
      en: en
      und: und
      zxx: zxx
user_search:
  advanced:
    types:
      supplemental: supplemental
      tweet: tweet
      blog: blog
      news: news
      safari: safari
      resource: resource
      country: country
      donate_page: donate_page
      staff: staff
      hostory: hostory
      history: history
      career: career
      landing_page: landing_page
      fact: fact
      project: project
      partner: partner
      landscape: landscape
      region: region
      species: species
      supplemental_sidebar: supplemental_sidebar
      hero_slideshow: hero_slideshow
      reasons: reasons
      ways_to_give: ways_to_give
    languages:
      en: en
      und: und
      zxx: zxx
