defaults:
  formatter: mandrill_mail
  sender: mandrill_mail
theme: current
modules:
  mandrill:
    none:
      formatter: mandrill_test_mail
      sender: mandrill_test_mail
  webform:
    none:
      formatter: mandrill_test_mail
      sender: mandrill_test_mail
  user:
    none:
      formatter: mandrill_mail
      sender: mandrill_mail
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
      sender: sendgrid_integration
  workbench_email:
    none:
      formatter: mandrill_mail
      sender: mandrill_mail
