mandrill_subaccount: null
mandrill_filter_format: plain_text
mandrill_track_opens: false
mandrill_track_clicks: false
mandrill_url_strip_qs: false
mandrill_analytics_campaign: ''
mandrill_batch_log_queued: false
mandrill_queue_worker_timeout: null
mandrill_log_defaulted_sends: true
mandrill_api_key: N5VsXgHUJFY7zq5UDuOMfQ
mandrill_api_timeout: 60
mandrill_api_classname: \Drupal\mandrill\DrupalMandrill
mandrill_mail_key_blacklist: ''
mandrill_process_async: false
_core:
  default_config_hash: 1voH1sN6U7SgNMXT8tdbT3CU2TtoqtB_xIKmn8i0VnM
mandrill_from_email: seangleason720@yahoo.com
mandrill_from_name: 'Sean gleason'
mandrill_analytics_domains: ''
