apikey: 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
test_defaults:
  to: sean.gleason@u.group
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: 'Sean Gleason'
  to_name: 'sean '
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
