apikey: ''
test_defaults:
  to: sean.gleason@u.group
  subject: 'Test Email from SendGrid Module'
  body:
    value: 'Test Message for SendGrid.'
    format: plain_text
  from_name: 'Sean Gleason'
  to_name: Ashton
  reply_to: seangleason720@yahoo.com
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
