data_source: maxmind_geoip2_bin_db
roles_to_geolocate:
  anonymous: anonymous
  authenticated: authenticated
  administrator: administrator
  editor: editor
  blogger: blogger
  junior_administrator: junior_administrator
  human_resources: human_resources
  junior_content_editor_our_staff: junior_content_editor_our_staff
  communications: communications
  media_relations: media_relations
  partner_administration: partner_administration
save_user_location_creation: true
roles_in_debug_mode:
  anonymous: false
  authenticated: false
  administrator: false
  editor: false
  blogger: false
  junior_administrator: false
  human_resources: false
  junior_content_editor_our_staff: false
  communications: false
  media_relations: false
  partner_administration: false
roles_in_debug_mode_ip:
  anonymous: 185.217.117.229
  authenticated: 185.217.117.229
  administrator: 185.217.117.229
  editor: ''
  blogger: ''
  junior_administrator: ''
  human_resources: ''
  junior_content_editor_our_staff: ''
  communications: ''
  media_relations: ''
  partner_administration: ''
allowed_pages: ''
eu_visitor_dont_save: false
timezone_format: identifier
_core:
  default_config_hash: 9Cx1wODaajnKKoHf-A1qO1Kh9Rgsbey-_19WUFDZPZA
