smtp_password: ''
smtp_on: false
smtp_host: ''
smtp_hostbackup: ''
smtp_port: ''
smtp_protocol: standard
smtp_username: ''
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '0'
smtp_debugging: false
